#pragma once

#ifndef _CHERRY_EXCEPTION_H
#define _CHERRY_EXCEPTION_H

///////////////////////////////////////////////////////////////////////////
///
/// \class		CCherryException
/// \brief		예외 enum을 나열한 wrapper 클래스
/// \author		ogoons
/// \date		2013-09-24
/// \remark		
/// \section	
///
///////////////////////////////////////////////////////////////////////////

class AFX_EXT_CLASS CCherryException
{
public:
	enum CHERRY_ERROR
	{
		// General
		ERROR_CHERRY_SUCCESS,
		ERROR_CHERRY_FAILURE,

		// CherryImage
		ERROR_IMAGE_FILE_NOT_FOUND,
		ERROR_IMAGE_LOAD_FAIL,
		ERROR_IMAGE_NOT_LOADED,
		ERROR_IMAGE_MAKE_IMAGE_FAIL,
		ERROR_IMAGE_UPDATE_CACHED_IMAGE_FAIL,
		ERROR_IMAGE_CACHED_IMAGE_NOT_LOADED,
		ERROR_IMAGE_DRAW_CACHED_IMAGE_FAIL,

		// CherryButton
		ERROR_BUTTON_CREATE_FAIL,

		// CherryToggleButton
		ERROR_TOGGLEBUTTON_CREATE_FAIL,

		// CherryCheckBox
		ERROR_CHECKBOX_CREATE_FAIL,

		// CherryRadioButton
		ERROR_RADIOBUTTON_CREATE_FAIL,

		// CherryComboBox
		ERROR_COMBOBOX_CREATE_FAIL,

		// CherryStatic
		ERROR_STATIC_CREATE_FAIL,

		// CherryLinkCtrl
		ERROR_LINKCTRL_CREATE_FAIL,

		// CherryEdit
		ERROR_EDIT_CREATE_FAIL,

		// CherryEditBackWnd
		ERROR_EDITBACKWND_CREATE_FAIL,

		// CherryImageCtrl
		ERROR_IMAGECTRL_CREATE_FAIL,

		// CherryAnimateImageCtrl
		ERROR_ANIMATEIMAGECTRL_CREATE_FAIL,
		ERROR_ANIMATEIMAGECTRL_IMAGE_NOT_FOUND,

		// CherryProgressCtrl
		ERROR_PROGRESSCTRL_CREATE_FAIL,
		ERROR_PROGRESSCTRL_RANGE_CURRENT_POS_LOW,

		// CherrySliderCtrl
		ERROR_SLIDERCTRL_CREATE_FAIL,
		ERROR_THUMB_CREATE_FAIL,

		// CherryListCtrl
		ERROR_LISTCTRL_CREATE_FAIL,
		ERROR_LISTCTRL_NOT_CREATED,

		// CherryHeaderCtrl
		ERROR_HEADERCTRL_CREATE_FAIL,

		// CherryTabCtrl
		ERROR_TABCTRL_CREATE_FAIL,
		ERROR_TABCTRL_NOT_CREATED,
		ERROR_TABCTRL_NOT_CREATED_PAGE_WINDOW,
		ERROR_TABCTRL_OUT_OF_BOUND,

		// CherryNotificationIcon
		ERROR_NOTIFICATIONICON_CREATE_FAIL,
		ERROR_NOTIFICATIONICON_NOT_CREATED,
		ERROR_NOTIFICATIONICON_NOT_ADDED,
		ERROR_NOTIFICATIONICON_FILE_NOT_FOUND,
		ERROR_NOTIFICATIONICON_INVALID_HANDLE,
		ERROR_NOTIFICATIONICON_ICON_LIST_EMPTY,
		ERROR_NOTIFICATIONICON_ICON_LIST_OUT_OF_BOUND,
		ERROR_NOTIFICATIONICON_INVALID_RANGE,
		ERROR_NOTIFICATIONICON_MEMORY_EXCEPTION,
		ERROR_NOTIFICATIONICON_LOAD_MENU_FAIL,
		ERROR_NOTIFICATIONICON_ALREADY_EXISTS_ID,
		ERROR_NOTIFICATIONICON_WIN2K_AND_LATER_AVAILABLE,
		ERROR_NOTIFICATIONICON_BALLOON_OPTION_DO_NOT_SUPPORTED_OS,
		ERROR_NOTIFICATIONICON_FLYOUT_CREATE_FAIL,

		// CherryNotificationDialog
		ERROR_NOTIFICATIONDIALOG_CREATE_FAIL,
	};
};

typedef CCherryException::CHERRY_ERROR CHERRY_RET;

#endif